(() => {
 'use strict';const $=s=>document.querySelector(s),store=window.LavishQuote,menu=$('#mobile-menu'),toggle=$('.menu-toggle');let requestText='';
 const closeMenu=()=>{menu.hidden=true;toggle.setAttribute('aria-expanded','false')};toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';menu.hidden=!open;toggle.setAttribute('aria-expanded',String(open))});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){closeMenu();toggle.focus()}});window.matchMedia('(min-width:901px)').addEventListener('change',closeMenu);
 function render(){const items=store.read();$('#quote-items').replaceChildren();$('#quote-empty').hidden=!!items.length;$('#quote-form').hidden=!items.length;$('#quote-summary').hidden=!items.length;$('#quote-item-count').textContent=`${items.length} selected ${items.length===1?'piece':'pieces'}`;
  items.forEach(item=>{const row=document.createElement('article');row.className='quote-row';const image=document.createElement('img');image.src=item.image.startsWith('assets/')?item.image:'assets/seating.webp';image.alt=item.name;const body=document.createElement('div'),heading=document.createElement('h3');heading.textContent=item.name;const tools=document.createElement('div');tools.className='quote-row-tools';const label=document.createElement('label'),input=document.createElement('input');input.id='qty-'+item.id.replace(/[^a-z0-9]/gi,'-');input.type='number';input.min=1;input.max=999;input.step=1;input.value=item.quantity;input.setAttribute('aria-label',`Quantity for ${item.name}`);label.textContent='Quantity';label.htmlFor=input.id;input.addEventListener('change',()=>{store.set(item.id,input.value);input.value=store.quantity(input.value)});const remove=document.createElement('button');remove.className='quote-remove';remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${item.name}`);remove.addEventListener('click',()=>{store.remove(item.id);render();$('#quote-item-count').focus()});tools.append(label,input,remove);body.append(heading,tools);row.append(image,body);$('#quote-items').append(row)});
 }
 render();const dialog=$('#quote-review');
 $('#quote-form').addEventListener('submit',e=>{e.preventDefault();const items=store.read();if(!items.length){render();return}const data=new FormData(e.currentTarget);requestText='LAVISH RENTAL QUOTE REQUEST\n\n'+items.map(x=>`${x.quantity} × ${x.name}`).join('\n')+'\n\n'+[['Name','name'],['Email','email'],['Phone','phone'],['Event date','date'],['City / venue','venue'],['Notes','notes']].map(([label,key])=>`${label}: ${data.get(key)||'Not specified'}`).join('\n');$('#quote-request-text').textContent=requestText;dialog.showModal();document.body.style.overflow='hidden'});
 $('#close-quote-review').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.style.overflow='';$('#review-request').focus({preventScroll:true})});
 $('#download-quote').addEventListener('click',()=>{const blob=new Blob([requestText],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lavish-rental-quote-request.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
})();
